### ISSUE TITLE
Mesmo após editar o perfil para `Sou palestrante` a aba `Sou organizador` continua ativa e vice-versa

### ISSUE THREAD

**Issue by GabrieleSuzart** [React-Bootcamp-WoMarkersCode/call-of-papers#192]
![image](https://user-images.githubusercontent.com/30198542/79934451-f27c1d80-8428-11ea-82e8-25390ed7b440.png)

É esperado que a aba fique desabilitada (ou não seja exibida) quando não contemplada pelo perfil

**Comment by GabrieleSuzart** [comment]
![image](https://user-images.githubusercontent.com/30198542/79991953-3f8fdc00-8489-11ea-9b05-5ffc6d231a80.png)
Talvez seja interessante salvar essa info no localStorage, volta e meia está bugando

**Comment by IsabellaSoares** [comment]
> ![image](https://user-images.githubusercontent.com/30198542/79991953-3f8fdc00-8489-11ea-9b05-5ffc6d231a80.png)
> Talvez seja interessante salvar essa info no localStorage, volta e meia está bugando

**Comment by IsabellaSoares** [comment]
> ![image](https://user-images.githubusercontent.com/30198542/79991953-3f8fdc00-8489-11ea-9b05-5ffc6d231a80.png)
> Talvez seja interessante salvar essa info no localStorage, volta e meia está bugando

@GabrieleSuzart  Já está sendo salvo no localStorage

![image](https://user-images.githubusercontent.com/32148199/80158634-5c1e3800-859f-11ea-9cab-e9204e189645.png)

Você acha que forçar o reload do componente do menu sempre que esse campo for alterado resolveria o problema?
