### ISSUE TITLE
É possível visualizar a area de submissao de palestras de um evento que não é meu, aprovar e recusar palestras

### ISSUE THREAD

**Issue by GabrieleSuzart** [React-Bootcamp-WoMarkersCode/call-of-papers#193]
![image](https://user-images.githubusercontent.com/30198542/79934735-a8e00280-8429-11ea-9f1c-e23deb4cce46.png)

Toda a area de submissão de palestras não deve ser exibida para pessoas que não são organizadores daquele evento.

**Comment by GabrieleSuzart** [comment]
@oliviaresende em minha defesa eu peguei esse bug antes do refactor que eu fiz rs

**Comment by oliviaresende** [comment]
@GabrieleSuzart em minha defesa como antes ia da tela de eventos para a submissions o bloqueio viria da tela de eventos rsrs
