### ISSUE TITLE
Área de parceiros

### ISSUE THREAD

**Issue by IsabellaSoares** [React-Bootcamp-WoMarkersCode/call-of-papers#21]
![partners](https://user-images.githubusercontent.com/32148199/76912333-475ccf00-6892-11ea-8aa2-f4e829564609.png)

**Comment by kathpallotta** [comment]
@IsabellaSoares me desculpa, eu passei batido por esse print da Campus Party... tinha entendido que a tela seria simplesmente um display dos partners, e não uma call for partners, rs. Vou adaptar melhor isso.
