### ISSUE TITLE
Rota incorreta

### ISSUE THREAD

**Issue by matancredi** [React-Bootcamp-WoMarkersCode/call-of-papers#232]
Quando o usuário não tem nenhuma palestra, este botão de cadastrar palestra está levando ao form sem considerar o id do evento, ou seja, vai dar erro no cadastro. O usuário precisa escolher o evento antes.

![image](https://user-images.githubusercontent.com/33610283/80213332-61b36680-860f-11ea-9a0e-6772d9047e94.png)

**Comment by matancredi** [comment]
![image](https://user-images.githubusercontent.com/33610283/80214658-9cb69980-8611-11ea-9f7d-b988633f8a86.png)
esse tb

**Comment by oliviaresende** [comment]
@matancredi esse segundo ta correto, é para cadastrar uma palestra sem evento para ser aproveitada quando o palestrante quiser.

**Comment by matancredi** [comment]
Entendi, não sabia que íamos ter essa opção, mas faz sentido. Vou fechar então.
