### ISSUE TITLE
Tela de "Home"

### ISSUE THREAD

**Issue by Alessandra-Nastassja** [React-Bootcamp-WoMarkersCode/call-of-papers#4]
![1 1](https://user-images.githubusercontent.com/27302446/76710994-a7187600-66ea-11ea-9112-7e76d2f6aa07.PNG)

**Descrição da página:**

_Usuário sem login_
- Menu (Login/Cadastrar
- Lista de eventos (descrição e botão de submeter palestra);
- Footer (Sobre e contato).

_Usuário com login_
- Menu (Home, Minhas palestras, Meus eventos e Meu perfil);
- Lista de eventos (descrição e botão de submeter palestra);
- Footer (Sobre e contato).

**Comment by IsabellaSoares** [comment]
[Exemplo com Ant Design](https://github.com/IsabellaSoares/Bootcamp-React-WomakersCode/tree/master/studio-ghibli-challenge)
